baseURL = 'https://vladdp.github.io/vladdp_pages/'
relativeURLs = true
languageCode = 'en-us'
title = 'Vlad P'
theme = 'hugo-book'


# hugo-pook config (refer to documentation)

[params]
    BookTheme = 'light'
    BookToC = false
    BookSearch = true
    BookComments = false


# image cache location

[caches]
  [caches.images]
    dir = ':cacheDir/images'